### ISSUE TITLE
IPS 4.2 inkompatibel

### ISSUE THREAD

**Issue by Nall-chan** [BrMrx/SymconHP#1]
RegisterTimer ist eine Funktion des SDK, bitte nicht mehr selbst überschreiben. Da IPS jetzt die internen Timer nutzt (und nicht mehr ein zyklisches Ereignis)
RegisterTimer darf auch nur im Create genutzt werden.
SetTimerInterval im Appylchanges nutzen um den Intervall zu ändern.

**Comment by saeitsystems** [comment]
Alle 4.2 inkompatibilitäten wurden behoben

**Comment by BrMrx** [comment]
Keine IP-Symcon Inkompatibilitäten mehr bekannt
