### ISSUE TITLE
Troll Basis DuoFern wird nicht als Rolladenaktor erkannt

### ISSUE THREAD

**Issue by wangard** [BrMrx/SymconHP#2]
Hallo,

ich habe Ihr Programm entdeckt und bin davon begeistert. Mit meinen Rolladenmotoren klappt es hervorragend. Neben den Rolladenmotoren setze ich aber noch zwei Troll Basis DuoFern ein. Diese werden jedoch nicht als Rolladenaktoren sondern als Schaltaktoren erkannt. Ist es möglich dies umzukonfigurieren? Wenn Sie irgendwelche Systemabzüge brauche, melden Sie sich einfach.

Vielen Dank

Patrick Wangard

**Comment by BrMrx** [comment]
Hallo Patrik,

ich war letzte Woche in Urlaub so das ich mich erst jetzt um das Problem kümmern kann.
Ich denke das ist nicht viel Arbeit....... Ich sehe mir das die Tage mal an.
LG
Bruno Marx

**Comment by BrMrx** [comment]
Da ich die Geräte nicht selber im Einsatz habe brauche ich zur Implementation der Unterstützung die genaue Fehlermeldung!!
Sieht deine Fehlermeldung so aus:
> 01.11.2017 20:34:20*| SymconHP*| unbekannter Typ 'Troll Comfort DuoFern' -> Standardbehandlung als Schalter

Wenn nicht, dann bitte die exacte IP-Symcon Fehlermeldung hier posten.
LG
Bruno

**Comment by BrMrx** [comment]
Hallo Patrik,
Ich habe den DuoFern Typ "Troll Comfort" eingebaut. Bitte prüfen und dann den "issue" schließen.
Sollte es sich in deinem Fall um ein weiteres DuFern Gerät handeln brauche ich die genaue IP-Symcon Fehlermeldung.

**Comment by BrMrx** [comment]
Da ich keine weitere Rückmeldung bekommen habe gehe ich davon sich das Problem damit erledigt hat

**Comment by wangard** [comment]
Hallo,

Sorry, dass ich mich erst jetzt melde. Mein Raspberry Pi war abgestürzt und ich musste Symcon erst neu installieren.

Ich bekomme die folgende Fehlermeldung:
22.11.2017 16:05:10 | SymconHP | unbekannter Typ 'Troll Basis DuoFern' -> Standardbehandlung als Schalter

Ich hoffe, dass Sie mir trotzdem noch helfen.

Vielen Dank

Patrick Wangard

**Comment by BrMrx** [comment]
Ich sehe es mir heute Abend mal an. Es gibt also wahrscheinlich einen "Troll Comfort" und einen Troll Basis".

**Comment by BrMrx** [comment]
Bin gestern nicht dazu gekommen, ich denke am Wochenende finde ich Zeit .....

**Comment by BrMrx** [comment]
Hallo Patrick,

die Änderungen für den 'Troll Basis DuoFern' sind jetzt drin.
Bitte überprüfen und den Issue schließen wenn alles läuft.

Gruß
Bruno

**Comment by wangard** [comment]
Wie bekomme ich denn nachträglich im Objektbaum die Variablen aktualisiert? Muss ich die Geräte löschen?

**Comment by BrMrx** [comment]
Hallo Patrick,

den Treiber über die Modulsteuerung aktualisieren und dann die zuvor fehlerhaft angelegten Objekte löschen und danach erneut abgleichen lassen.
Dannach sollte alles laufen.

**Comment by wangard** [comment]
Klappt alles super!

Vielen Dank!

Patrick
