### ISSUE TITLE
IPS 7

### ISSUE THREAD

**Issue by sieckendieck** [BrMrx/SymconHP#3]
Hallo,

IPS ist jetzt als 7.0 in der Testing Phase.
Leider funktioniert das Modul damit nicht mehr.
Wir es eine Anpassung geben?

Gruß
Mike

**Comment by BrMrx** [comment]
Hallo Mike,

Ich habe keine Zeit den Treiber in der Test Phase auf IPS 7.0 anzupassen. Vielleicht hat hier jemand anderes Interesse und Zeit dies zu tuen.
Wenn IPS 7.0 freigegeben ist, werde ich sehen welche Anpassungen notwendig sind.
Gibt es den irgendwelche Fehlermeldungen beim Laden des Moduls die einen Hinweis auf den Aufwand geben würden?

Gruß
Bruno

**Comment by BrMrx** [comment]
Das Modul läuft jetzt unter IPS 7
